#!/usr/bin/env python3
import json, random, warnings

if __name__ == '__main__':
    import sys, argparse
    parser = argparse.ArgumentParser(
            prog = 'jsonlctx',
            description = 'Outputs jsonl from input, varying the character length of the output.',
        )
    parser.add_argument('--max', type=int, default=4096*4)
    parser.add_argument('--min', type=int, default=1024*4)
    parser.add_argument('--input','-i', type=argparse.FileType('rt'), default=sys.stdin)
    parser.add_argument('--output','-o', type=argparse.FileType('wt'), default=sys.stdout)
    args = parser.parse_args()

    assert args.min > 0
    assert args.max >= args.min
    ID = 101 
    while True:
        ctxlen = round(random.random() * (args.max - args.min) + args.min)
        try:
            text = args.input.read(round(random.random() * (args.max - args.min) + args.min))
        except Exception as e:
            warnings.warn(e)
            continue
        if not len(text):
            break
        json.dump(
                dict(
                        meta=dict(ID=ID),
                        text=text,
                    ),
                args.output,
                ensure_ascii=False,
            )
        args.output.write('\n')
        ID += 1

